# Generated by Django 3.0 on 2019-12-22 01:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0002_auto_20191217_1342'),
        ('game', '0003_auto_20191217_0708'),
    ]

    operations = [
        migrations.CreateModel(
            name='OnlineGame',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isStarted', models.BooleanField(default=False)),
                ('password', models.CharField(max_length=20)),
                ('curround', models.IntegerField(default=0)),
                ('phrasePack', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='game.PhrasePack')),
                ('players', models.ManyToManyField(to='user_profile.Profile')),
            ],
        ),
    ]
