# Generated by Django 3.0 on 2019-12-23 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0008_remove_onlinegame_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='onlinegame',
            name='curround',
            field=models.IntegerField(default=0),
        ),
    ]
