# Generated by Django 3.0 on 2019-12-23 05:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0009_onlinegame_curround'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='round',
            name='mainscore',
        ),
        migrations.RemoveField(
            model_name='round',
            name='score1',
        ),
        migrations.RemoveField(
            model_name='round',
            name='score2',
        ),
        migrations.RemoveField(
            model_name='round',
            name='score3',
        ),
        migrations.RemoveField(
            model_name='round',
            name='score4',
        ),
        migrations.RemoveField(
            model_name='round',
            name='score5',
        ),
        migrations.RemoveField(
            model_name='round',
            name='score6',
        ),
        migrations.RemoveField(
            model_name='round',
            name='score7',
        ),
    ]
