# Generated by Django 3.0 on 2019-12-22 23:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0005_auto_20191222_1911'),
        ('game', '0006_remove_image_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='onlinegame',
            name='curround',
        ),
        migrations.CreateModel(
            name='Round',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('finished', models.BooleanField(default=False)),
                ('mainscore', models.IntegerField(default=0)),
                ('score1', models.IntegerField(default=0)),
                ('score2', models.IntegerField(default=0)),
                ('score3', models.IntegerField(default=0)),
                ('score4', models.IntegerField(default=0)),
                ('score5', models.IntegerField(default=0)),
                ('score6', models.IntegerField(default=0)),
                ('score7', models.IntegerField(default=0)),
                ('image', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='game.Image')),
                ('phrases', models.ManyToManyField(to='game.Phrase')),
                ('player', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='user_profile.Profile')),
            ],
        ),
        migrations.AddField(
            model_name='onlinegame',
            name='rounds',
            field=models.ManyToManyField(to='game.Round'),
        ),
    ]
