# Generated by Django 3.0 on 2019-12-22 23:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0007_auto_20191223_0240'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='onlinegame',
            name='password',
        ),
    ]
