# Generated by Django 3.0 on 2019-12-23 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0010_auto_20191223_0818'),
    ]

    operations = [
        migrations.AddField(
            model_name='onlinegame',
            name='playersready',
            field=models.IntegerField(default=0),
        ),
    ]
