# Generated by Django 3.0 on 2019-12-25 22:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0007_auto_20191226_0128'),
        ('game', '0011_onlinegame_playersready'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayersNewPhrase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ground', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.Round')),
                ('newPhrase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.Phrase')),
                ('player', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='user_profile.Profile')),
            ],
        ),
        migrations.CreateModel(
            name='PlayersChoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chosenPhrase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.Phrase')),
                ('ground', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.Round')),
                ('player', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='user_profile.Profile')),
            ],
        ),
    ]
