# Generated by Django 3.0 on 2019-12-26 00:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0013_auto_20191226_0150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playersnewphrase',
            name='newPhrase',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='game.Phrase'),
        ),
    ]
