# Generated by Django 3.0 on 2019-12-26 00:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0015_auto_20191226_0320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playerschoice',
            name='chosenPhrase',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.Phrase'),
        ),
        migrations.AlterField(
            model_name='playersnewphrase',
            name='newPhrase',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.Phrase'),
        ),
    ]
