# Generated by Django 3.0 on 2019-12-25 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0006_profile_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='isReady',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='rating',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=3),
        ),
    ]
