# Generated by Django 3.0 on 2019-12-25 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0007_auto_20191226_0128'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='isReady',
        ),
        migrations.AddField(
            model_name='profile',
            name='waitingFor',
            field=models.IntegerField(default=0),
        ),
    ]
